---
- name: Deploy Laravel with Docker Compose
  hosts: web_servers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  
  vars:
    ansible_python_interpreter: /usr/bin/python3  

  tasks:
    - name: Update apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"    

    - name: Install docker-compose Python module
      ansible.builtin.pip:
        name: docker-compose

    - name: Allow SSH (port 22)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      become: yes

    - name: Allow HTTP (port 80)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
      become: yes

    - name: Allow HTTPS (port 443)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
      become: yes

    - name: Create iptables directory
      file:
        path: /etc/iptables
        state: directory
      become: yes
      
    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4
      become: yes
      changed_when: false

    - name: Copy Docker Compose configuration
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
    
    - name: Run Docker Compose
      ansible.builtin.docker_compose:
        project_src: /home/ubuntu
        project_name: laravel
        state: present